1		!Aircraft Control on or off
-0.02	!Kpy Proportional gain on crossrange (airplane)
0.1		!Kdy Derivative gain on crossrange (airplane)
-0.8	!Kpsi Proportional gain on heading (airplane)
1.2		!Kpp proportional gain on roll angle (airplane)
0.1		!Kdp Derivative gain on roll angle (airplane)
-0.4	!Kpz Proportional gain on altitude (airplane)
0.15	!Kdz Derivative gain on altitude (airplane)
-0.3	!Kpt Proportional gain on pitch (airplane)
-0.15	!Kv proportional gain on sideslip (airplane)
2.0		!Ku proportional gain on speed (airplane)    
1	!Feedback Update Rate(Hz)
1	!Turn On Sensor Errors

